### ISSUE TITLE
PR for package installation method?

### ISSUE THREAD

**Issue by solarkennedy** [justinclayton/puppet-module-serf#4]
So there is this other puppet-serf module that I did this PR for: https://github.com/davidcollom/puppet-serf/pull/7

But I think long term this module will be easier to maintain as Serf evolves, by sticking with the `hash=>json` config route. 

If I did a similar PR to your module for installing via packages (I personally think is a must at larger scale), would it be accepted?

**Comment by justinclayton** [comment]
Absolutely! I wasn't aware that serf was available in package form, so that's great news.

I'll close this issue and wait for your PR!

**Comment by solarkennedy** [comment]
Heh, it isn't packaged by upstream, but I'm sure there are others out there like me who prefer to distribute binaries as system packages when at scale. 

At some point having your infrastructure depending on external sites (bintray) and having 1000 servers downloading a zip file from there doesn't make sense.
